In [4]:
####1. Python program to add two Matrices
Y = [[5,8,1],
[6,7,3],
[4,5,9]]
result = [[0,0,0],
[0,0,0],
[0,0,0]]
# iterate through rows
for i in range(len(X)):
    # iterate through columns
    for j in range(len(X[0])):
        result[i][j] = X[i][j] + Y[i][j]
        for r in result:
            print(r)

NameError: name 'X' is not defined

In [9]:
####2. Python program to multiply two matrices
X = [[12,7,3],
[4 ,5,6],
[7 ,8,9]]
A = [[12, 7, 3],
[4, 5, 6],
[7, 8, 9]]
# take a 3x4 matrix
B = [[5, 8, 1, 2],
[6, 7, 3, 0],
[4, 5, 9, 1]]
result = [[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]]
# iterating by row of A
for i in range(len(A)):
    # iterating by column by B
    for j in range(len(B[0])):
        # iterating by rows of B
        for k in range(len(B)):
             result[i][j] += A[i][k] * B[k][j]
             for r in result:
                 print(r)


[60, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[102, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 96, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 145, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 12, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 33, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 24]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 24]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[20, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[50, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 32, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 67, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 97, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 97, 4, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 97, 19, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 97, 73, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 97, 73, 8]
[0, 0, 0, 0]
[114, 160, 60

In [10]:
#####3. Python program for Matrix Product
X = [[12,7,3],
[4 ,5,6],
[7 ,8,9]]
A = [[12, 7, 3],
[4, 5, 6],
[7, 8, 9]]
# take a 3x4 matrix
B = [[5, 8, 1, 2],
[6, 7, 3, 0],
[4, 5, 9, 1]]
result = [[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]]
# iterating by row of A
for i in range(len(A)):
# iterating by column by B
    for j in range(len(B[0])):
    # iterating by rows of B
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]
            for r in result:
                print(r)

[60, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[102, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 96, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 145, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 12, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 33, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 24]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 24]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[20, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[50, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 32, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 67, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 97, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 97, 4, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 97, 19, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 97, 73, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 97, 73, 8]
[0, 0, 0, 0]
[114, 160, 60

In [11]:
####4. Adding and Subtracting Matrices in Python
import numpy as np
# creating first matrix
A = np.array([[1, 2], [3, 4]])
# creating second matrix
B = np.array([[4, 5], [6, 7]])
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


In [13]:
####5. Transpose a matrix in Single line in Python
m = [[1,2],[3,4],[5,6]]
for row in m :
    print(row)
    rez = [[m[j][i] for j in range(len(m))] for i in range(len(m[0]))]
    print("\n")
    for row in rez:
       print(row)

[1, 2]


[1, 3, 5]
[2, 4, 6]
[3, 4]


[1, 3, 5]
[2, 4, 6]
[5, 6]


[1, 3, 5]
[2, 4, 6]


In [19]:
####6. Python | Matrix creation of n*n
N = 4
# printing dimension
print("The dimension : " + str(N))
# using list comprehension
# matrix creation of n * n
res = [list(range(1 + N * i, 1 + N * (i + 1)))for i in range(N)]
    # print result
print("The created matrix of N * N: " + str(res))


The dimension : 4
The created matrix of N * N: [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [21]:
###7. Python | Get Kth Column of Matrix
test_list = [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
# printing original list
print("The original list is : " + str(test_list))
# initialize K
K = 2
res = [sub[K] for sub in test_list]
# printing result
print("The Kth column of matrix is : " + str(res))

The original list is : [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
The Kth column of matrix is : [6, 10, 5]


In [23]:
###8. Python – Vertical Concatenation in Matrix
test_list = [["Gfg", "good"], ["is", "for"], ["Best"]]
# printing original list
print("The original list : " + str(test_list))
# using loop for iteration
res = []
N = 0
while N != len(test_list):
    temp = ''
    for idx in test_list:
    # checking for valid index / column
        try: temp = temp + idx[N]
        except IndexError: pass
        res.append(temp)
        N = N + 1
        res = [ele for ele in res if ele]
        # printing result
        print("List after column Concatenation : " + str(res))

The original list : [['Gfg', 'good'], ['is', 'for'], ['Best']]
List after column Concatenation : ['Gfg']
List after column Concatenation : ['Gfg', 'Gfgfor']
List after column Concatenation : ['Gfg', 'Gfgfor', 'Gfgfor']


In [25]:
####9. Python program to check if a string is palindrome or not
def isPalindrome(s):
    return s == s[::-1]
# Driver code
s = "malayalam"
ans = isPalindrome(s)
if ans:
    print("Yes")
else:
    print("No")

Yes


In [40]:
####10.Python program to check whether the string is Symmetrical or Palindrome
def palindrome(a):
    mid = (len(a)-1)//2
    start = 0
    last = len(a)-1
    flag = 0
    # A loop till the mid of the
    # string
    while(start <= mid):
    # comparing letters from right
    # from the letters from left
        if (a[start]== a[last]):
                start += 1
                last -= 1
        else:
             flag = 1
             break;
            # Checking the flag variable to
            # check if the string is palindrome
            # or not
        if flag == 0:
                 print("The entered string is palindrome")
            else:
                 print("The entered string is not palindrome")
def symmetry(a):
                n = len(a)
                flag = 0
                # Check if the string's length
                # is odd or even
                if n%2:
                mid = n//2 +1
                else:
                mid = n//2
                start1 = 0
                start2 = mid
                while(start1 < mid and start2 < n):
                if (a[start1]== a[start2]):
                start1 = start1 + 1
                start2 = start2 + 1
                else:
                flag = 1
                break
                # Checking the flag variable to
                # check if the string is symmetrical
                # or not
                if flag == 0:
                print("The entered string is symmetrical")
                else:
                print("The entered string is not symmetrical")
                string = 'amaama'
                palindrome(string)
                symmetry(string)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 21)